### ISSUE TITLE
Enhancement: Spawn conditions for variants

### ISSUE THREAD

**Issue by gaforb** [Nebby1999/VarianceAPI#2]
Just a few ideas of varying difficulty to implement, such as:

- [x] Variants that only spawn on specific stages
- [x] Variants that only spawn post-loop
- [x] Variants that spawn if certain items are in a player's inventory
- Such as Ghost of Kjaro/Runald only spawning if a player has their bands.
- [ ] Variants that spawn when a certain number of (a type of) monsters have died
- For example, could be used to make an invulnerable monster that punishes farming hidden realms for xp/items.
- [ ] Variants that spawn (or can't spawn) based on what other variants are alive
- For example, could be used to make a "summoning" variant which if not killed quickly calls in a much more powerful variant.
- Could also prevent multiple of a powerful / unique variant from appearing.

Thanks for your time, and for the great work on this mod! :)

**Comment by Nebby1999** [comment]
These are excellent ideas to be honest. Most of these (Such as specific stage variants, post loop ones, etc) have been an idea in my head for the past couple of weeks.

Currently as it stands consider a good chunk of these done when the next big major update comes out (Update that'll come after the dlc update)

Reason why i'm pushing this feature to that update is because the Adresasbles change will definetly break my mod, and i was planning on refactoring entirely how the spawning system works since that would also fix an issue regarding the "Unique" boolean in the config files.
